[package]
name = "awconf"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.11.0", default-features = false, features = ["toml"] }
dirs = "4.0.0"
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
