[package]
name = "awconf"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { version = "0.11", default-features=false, features = ["toml"] }
dirs = "3.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
